name: Build Release for each available platform

on: [push]

jobs:
  build-ubuntu:

    runs-on: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - name: Setup latest CMake and Ninja
      uses: lukka/get-cmake@latest
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
    
    - name: Install NPM dependencies
      run: npm install
    
    - name: Build Release
      run: npm run cmake:rebuild-release
      
    - name: Upload output file
      uses: actions/upload-artifact@v2
      with:
        name: output-log-file
        path: output.log
